pipeline {
    agent any

    stages {
        stage('Docker Build & Deploy') {
            steps {
                dir('AI/chatbot') {
                    script {
                        echo "🚀 Stopping existing chatbot server (if any)"
                        sh """
                        docker stop chatbot-app || true
                        docker rm chatbot-app || true
                        """

                        echo "🚀 Building Docker Image for yolo_gemini"
                        sh """
                        docker build --no-cache -t chatbot-app .
                        """

                        echo "🚀 Running yolo_gemini FastAPI server"
                        sh """
                        docker run -d --name chatbot-app \
                        -v /home/ubuntu/project/chatbotAI/secret/.env:/app/.env \
                        -p 8000:8000 chatbot-app
                        """
                    }
                }
            }
        }
    }
}
