export const QUERY_KEYS = {
  GROUPS: 'groups',
  MEMBERS: 'members',
  ONBOARDING: 'onboarding',
  OAUTH: 'oauth',
  PHOTOCARDS: 'photocards',
  LIKED_GROUPS: 'likedGroups',
  LIKED_MEMBERS: 'likedMembers',
  POST_LIST: 'postList',
  POST_DETAIL: 'postDetail',
  SELLER_LIST: 'sellerList',
  ALBUMS: 'albums',
  MYCARD: 'mycard',
  OTHERSCARD: 'otherscard',
  POST_CHAT_ROOMS: 'postChatRooms',
  EXCHANGE_CHAT_ROOMS: 'exchangeChatRooms',
  CHAT_ROOM_DETAIL: 'chatRoomDetail',
  UNREAD_MESSAGE_COUNT: 'unreadMessageCount',
} as const;
