pipeline {
    agent any

    options {
        skipDefaultCheckout(false)
    }

    stages {
        stage('Copy Config') {
            steps {
                sh '''
                cp /pocketing/fe/.env FE/.env
                '''
            }
        }

        stage('Docker Build & Deploy') {
            steps {
                dir('FE') {
                    sh '''
                    docker compose version
                    docker compose -f /pocketing/docker-compose.pocketing.yml stop frontend
                    docker compose -f /pocketing/docker-compose.pocketing.yml rm -f frontend
                    docker compose -f /pocketing/docker-compose.pocketing.yml up -d --build frontend
                    '''
                }
            }
        }
    }
}