# 전역 설정 (Global Configuration)
worker_processes auto;

events {
    worker_connections 1024;
}

# HTTP 설정
http {
    include /etc/nginx/conf.d/*.conf;
    
    # MIME 타입 설정
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 기본 서버 블록 (HTTP)
    server {
        listen 80;
        server_name pocketing.app;
        return 301 https://$host$request_uri;
    }

    # HTTPS 서버 블록
    server {
        listen 443 ssl;
        server_name pocketing.app;

        ssl_certificate /etc/letsencrypt/live/pocketing.app/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pocketing.app/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        # API 프록시 - Spring Boot 서버로 요청 전달
        location /api/ {
            proxy_pass http://app_servers/api/; # upstream app_servers로 proxy_pass 대상 변경
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # FastAPI 프록시 - FastAPI 서버로 요청 전달
        location /fastapi/ {
            client_max_body_size 20M;
            
            proxy_pass http://pocketing.app:8000/fastapi/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 웹소켓 프록시
        location /ws/ {
            proxy_pass http://app_servers/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }

        # 챗봇 웹소켓 프록시
        location /chatbot/ws {
            proxy_pass http://pocketing.app:8000/chatbot/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            # ← 여기부터 추가
            proxy_set_header   Host              $host;
            proxy_buffering     off;
            proxy_read_timeout  300s;
            # ← 여기까지
        }
    }
}
