pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('BE') {
                    sh '''
                    chmod +x gradlew
                    ./gradlew clean build -x test
                    '''
                }
            }
        }

        stage('Copy Config From Container') {
            steps {
                sh '''
                docker cp backend:/resources/application.yml BE/src/main/resources/application.yml
                docker cp backend:/resources/application-prod.yml BE/src/main/resources/application.yml
                docker cp backend:/resources/firebase-service-account.json BE/src/main/resources/firebase-service-account.json
                '''
            }
        }

        stage('Deploy') {
            steps {
                dir('BE') {
                    sh '''
                    docker compose version
                    docker compose -f /pocketing/docker-compose.pocketing.yml stop backend
                    docker compose -f /pocketing/docker-compose.pocketing.yml rm -f backend
                    docker compose -f /pocketing/docker-compose.pocketing.yml build --no-cache backend
                    docker compose -f /pocketing/docker-compose.pocketing.yml up -d backend
                    '''
                }
            }
        }
    }
}
