pipeline {
    agent any

    options {
        skipDefaultCheckout(false)
    }

    stages {
        stage('Copy Config') {
            steps {
                sh '''
                mkdir -p BE/src/main/resources/
                cp /backend/secret/application.yml BE/src/main/resources/
                cp /backend/secret/application-prod.yml BE/src/main/resources/
                '''
            }
        }

        stage('Build') {
            steps {
                dir('BE') {
                    sh '''
                    chmod +x gradlew
                    ./gradlew clean build -x test
                    '''
                }
            }
        }

        stage('Docker Build & Deploy') {
            steps {
                dir('BE') {
                    sh '''
                    docker stop backend-app || true
                    docker rm backend-app || true
                    docker build -t backend-app .
                    docker run -d --name backend-app -p 8081:8080 backend-app
                    '''
                }
            }
        }
    }
}
